# Generated by Django 3.1.2 on 2020-10-10 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(null=True)),
                ('project_name', models.CharField(max_length=250)),
                ('project_synopsis', models.CharField(max_length=1000)),
                ('project_description', models.CharField(max_length=100000)),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_user', to=settings.AUTH_USER_MODEL)),
                ('project_collaborators', models.ManyToManyField(blank=True, to='users.Project')),
            ],
        ),
    ]
