# Generated by Django 3.1.2 on 2020-10-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='header_bg',
            field=models.ImageField(null=True, upload_to='media/photos/profile_headers'),
        ),
    ]
