# Generated by Django 3.1.2 on 2020-10-13 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_remove_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_1', models.ImageField(upload_to='media/projects')),
                ('pic_2', models.ImageField(upload_to='media/projects')),
                ('pic_3', models.ImageField(upload_to='media/projects')),
                ('pic_4', models.ImageField(upload_to='media/projects')),
                ('pic_5', models.ImageField(upload_to='media/projects')),
                ('pic_6', models.ImageField(upload_to='media/projects')),
                ('pic_7', models.ImageField(upload_to='media/projects')),
                ('pic_8', models.ImageField(upload_to='media/projects')),
                ('pic_9', models.ImageField(upload_to='media/projects')),
                ('pic_10', models.ImageField(upload_to='media/projects')),
                ('pic_11', models.ImageField(upload_to='media/projects')),
                ('pic_12', models.ImageField(upload_to='media/projects')),
                ('pic_13', models.ImageField(upload_to='media/projects')),
                ('pic_14', models.ImageField(upload_to='media/projects')),
                ('pic_15', models.ImageField(upload_to='media/projects')),
                ('pic_16', models.ImageField(upload_to='media/projects')),
                ('pic_17', models.ImageField(upload_to='media/projects')),
                ('pic_18', models.ImageField(upload_to='media/projects')),
                ('pic_19', models.ImageField(upload_to='media/projects')),
                ('pic_20', models.ImageField(upload_to='media/projects')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='pic',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.FileField(null=True, upload_to='path/to/img'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(null=True)),
                ('project_name', models.CharField(max_length=250)),
                ('project_synopsis', models.CharField(max_length=1000)),
                ('project_description', models.CharField(max_length=100000)),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_user', to=settings.AUTH_USER_MODEL)),
                ('project_collaborators', models.ManyToManyField(blank=True, to='feed.Project')),
                ('project_pics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='feed.projectpics')),
            ],
        ),
    ]
