# Generated by Django 3.1.2 on 2020-10-13 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0004_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=250)),
                ('story_caption', models.CharField(max_length=500)),
                ('story_datetime', models.DateTimeField(auto_now=True)),
                ('story_pic', models.ImageField(upload_to='media/photos/stories')),
                ('story_vid', models.FileField(upload_to='media/videos/stories')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
