# Generated by Django 3.1.2 on 2020-10-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_pics',
        ),
        migrations.AddField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(null=True, upload_to='media/projects'),
        ),
        migrations.DeleteModel(
            name='ProjectPics',
        ),
    ]
